### PR TITLE
Add melpa badges

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Just adding melpa badges.

(I'm working on [cask-package-toolset](https://github.com/AdrieanKhisbe/cask-package-toolset.el), and I plan to integrate undercover ;))

### CODE REVIEW

**Comment by sviridov** [comment]
@AdrieanKhisbe, thank you! But I can see some markdown typos [here](https://github.com/AdrieanKhisbe/undercover.el/blob/features/badge/README.md). Please remove redundant 
parentheses and place badges on the same line. Then I will merge it.

**Comment by AdrieanKhisbe** [comment]
Done. There ~~is~~ was a bug in my cpt templates ^^

**Comment by AdrieanKhisbe** [comment]
(by the way tell me if you prefer all the badge on the same line. and if so, on or below the title)

**Comment by sviridov** [comment]
> (by the way tell me if you prefer all the badge on the same line. and if so, on or below the title)

Yeah, I prefer them on the same line with title. Should be enough space.

**Comment by AdrieanKhisbe** [comment]
*voilà :)*

**Comment by sviridov** [comment]
@AdrieanKhisbe Oh, I'm sorry, Github preview confused me!:) [README file](https://github.com/AdrieanKhisbe/undercover.el/blob/features/badge/README.md) and [Github page](https://github.com/AdrieanKhisbe/undercover.el/tree/features/badge) looks differently. It's not enough space... Please place all bages on new line. I swear it will be final fix!

**Comment by AdrieanKhisbe** [comment]
No problemo :)

**Comment by sviridov** [comment]
@AdrieanKhisbe Thank you! Merged.

**Pull request merged**
